### ISSUE TITLE
Dropdown needs second click to open (sometimes)

### ISSUE THREAD

**Issue by tomidix** [BlazorFluentUI/BlazorFluentUI#317]
Sometimes, when the page is just loaded, we need 2 clicks on dropdown to open it.

This also applies to demo page: https://www.blazorfluentui.net/dropdownPage
To reproduce, open the page, click on first dropdown then use f5 and immediately after dropdowns are loaded click on same dropdown as first time.
On first click it seems it is only focused; on second click it opens.

It does not happen every time so maybe couple of refresh attempts will be needed.

**Comment by vnbaaij** [comment]
Yes, I've seen that behavior too. Seems it got introduced with the JS Isolation in 5.2. Will investigate but don't think it will be an easy find/fix

**Comment by vnbaaij** [comment]
It seems to have been fixed in 5.3.1. Further testing needed...

**Comment by tomidix** [comment]
I'll report back in a day or two..

**Comment by tomidix** [comment]
@vnbaaij Can you just publish the nuget package out?

**Comment by vnbaaij** [comment]
Done!

**Comment by tomidix** [comment]
It's definitely better but I need some more time as sometimes I still have the problems and haven't figure out how exactly is it reproduced.

**Comment by tomidix** [comment]
for v5.3.1.0
to reproduce every time: 
- reload demo dropdown page (with f5) while having mouse on the dropdown position.. click it as soon as it shows

to reproduce sometimes (this doesn't happen every time):
- load https://www.blazorfluentui.net/labelPage
- switch between some pages (other than dropdown page, 3-4 pages)
- finally select dropdown page, leave it to load fully 2-3 seconds
- click on the first dropdown -> should be only selected
- 2nd click opens dropdown
- go back to labelPage
- press F5 and repeat the process

**Comment by vnbaaij** [comment]
Cannot reproduce anymore with these steps on 5.3.2. Closing for now.
